name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [14, 16]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node }}.x
        uses: actions/setup-node@main
        with:
          node: ${{ matrix.node }}
          check-latest: true
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node }}-build-
            ${{ runner.os }}-
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Lint
        run: |
          pnpm install
          pnpm run lint
