name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16, 18]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node }}-build-
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run lint
