name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16, 18]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: pnpm
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run lint
